FROM gcr.io/tensorflow/tensorflow:latest
MAINTAINER Stefano Picozzi <StefanoPicozzi@gmail.com>

RUN lsb_release -a

RUN echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" | tee -a /etc/apt/sources.list
RUN cat /etc/apt/sources.list
RUN gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
RUN gpg -a --export E084DAB9 | apt-key add -
RUN apt-get update 
RUN apt-get install -y wget gdebi-core apt-transport-https \
                       locales libcurl4-openssl-dev libssl-dev libssh2-1-dev vim \
                       python-virtualenv mlocate git sudo libedit2 libapparmor1 \
                       psmisc python-setuptools iputils-ping \
                       r-cran-ggplot2

RUN cd /tmp; wget http://launchpadlibrarian.net/317977813/libicu57_57.1-4ubuntu0.2_amd64.deb
RUN cd /tmp; wget http://ftp.br.debian.org/debian/pool/main/r/readline/libreadline7_7.0-3_amd64.deb
RUN cd /tmp; wget http://ftp.br.debian.org/debian/pool/main/libp/libpng1.6/libpng16-16_1.6.28-1_amd64.deb
RUN cd /tmp; wget http://archive.ubuntu.com/ubuntu/pool/universe/r/r-base/r-base-core_3.4.2-1ubuntu1_amd64.deb
RUN cd /tmp; wget http://archive.ubuntu.com/ubuntu/pool/universe/r/r-base/r-base-dev_3.4.2-1ubuntu1_all.deb
RUN cd /tmp; dpkg -i libicu57*.deb
RUN cd /tmp; dpkg -i libread*.deb
RUN cd /tmp; dpkg -i libpng*.deb
RUN cd /tmp; dpkg -i r-base-core_3.4.2*.deb
RUN cd /tmp; dpkg -i r-base-dev_3.4.2*.deb
# RUN apt-get install -y r-base-core=3.4.2-1xenial1 r-base-dev=3.4.2-1xenial1
RUN R --version

# RUN apt-get install -y --no-install-recommends r-base-dev=3.4.2-1xenial1
# Install R
# https://cran.rstudio.com/bin/linux/ubuntu/README.html
# Dockerfile example at https://github.com/rocker-org/rocker-versioned/blob/master/r-ver/Dockerfile
ENV R_VERSION=${R_VERSION:-3.4.2} \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    TERM=xterm
RUN apt-get update
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen 
RUN locale-gen en_US.utf8
RUN /usr/sbin/update-locale LANG=en_US.UTF-8

# Install RStudio
# https://www.rstudio.com/products/rstudio/download-server/
# Dockerfile example at https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/Dockerfile
RUN cd /tmp; wget https://download2.rstudio.org/rstudio-server-1.1.383-amd64.deb
RUN cd /tmp; gdebi -n rstudio-server-1.1.383-amd64.deb

# Create rstudio user
RUN useradd rstudio \
    && echo "rstudio:rstudio" | chpasswd \
	&& mkdir /home/rstudio \
	&& chown rstudio:rstudio /home/rstudio \
	&& addgroup rstudio staff 

RUN updatedb
# Set up S6 init system
RUN wget -P /tmp/ https://github.com/just-containers/s6-overlay/releases/download/v1.11.0.1/s6-overlay-amd64.tar.gz \
    && tar xzf /tmp/s6-overlay-amd64.tar.gz -C / \
    && mkdir -p /etc/services.d/rstudio \
    && echo '#!/bin/bash \
    \n exec /usr/lib/rstudio-server/bin/rserver --server-daemonize 0' \
    > /etc/services.d/rstudio/run \
    && echo '#!/bin/bash \
    \n rstudio-server stop' \
    > /etc/services.d/rstudio/finish

# Launch rstudio-server
USER root
EXPOSE 8787
CMD ["/init"]
