options(encoding = "UTF-8")
Sys.setenv(CUDNN_VERSION="6.0.21")
Sys.setenv(NVIDIA_VISIBLE_DEVICES="all")
Sys.setenv(LD_LIBRARY_PATH="/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64/stubs:/usr/lib/R/lib")
Sys.setenv(NVIDIA_DRIVER_CAPABILITIES="compute,utility")
Sys.setenv(PATH="/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin")
Sys.setenv(CUDA_PKG_VERSION="8-0=8.0.61-1")
Sys.setenv(CUDA_VERSION="8.0.61")
Sys.setenv(NVIDIA_CUDA_VERSION="8.0.61")
