---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tf-rstudio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tf-rstudio
    spec:
      volumes:
      - name: lib
        hostPath:
          path: /var/lib/nvidia-docker/volumes/nvidia_driver/384.90
      - name: rstudio
        hostPath:
          path: /home/spicozzi/MLOps/rstudio
      containers:
      - name: tf-rstudio
        securityContext:
          privileged: true
        image: stefanopicozzi/tf-rstudio:latest
        ports:
        - containerPort: 8787
        resources:
          requests:
            alpha.kubernetes.io/nvidia-gpu: 1        
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        imagePullPolicy	:	Never
        volumeMounts:
        - mountPath: /usr/local/nvidia
          name: lib
          readOnly: true
        - mountPath: /home/rstudio
          name: rstudio
---
apiVersion: v1
kind: Service
metadata:
  name: tf-rstudio-service
  labels:
    app: tf-rstudio
spec:
  selector:
    app: tf-rstudio
  ports:
  - port: 8787
    protocol: TCP
    nodePort: 30787
  type: LoadBalancer
---

