apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: 2017-11-07T20:50:19Z
  generation: 2
  labels:
    run: tensorflow
  name: tensorflow
  namespace: mlops
  resourceVersion: "254647"
  selfLink: /apis/extensions/v1beta1/namespaces/mlops/deployments/tensorflow
  uid: 4405c947-c3fd-11e7-a20f-001fc69bc452
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tensorflow
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: tensorflow
    spec:
      containers:
      - image: gcr.io/tensorflow/tensorflow:latest-gpu
        imagePullPolicy: Never
        name: tensorflow
        ports:
        - containerPort: 8888
          protocol: TCP
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/local/nvidia/lib
          name: lib
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/lib/nvidia-384/bin
          type: ""
        name: bin
      - hostPath:
          path: /usr/lib/nvidia-384
          type: ""
        name: lib
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-11-07T20:50:19Z
    lastUpdateTime: 2017-11-07T20:50:19Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: tensorflow
  labels:
    app: tensorflow
spec:
  selector:
    app: tensorflow
  ports:
  - port: 8888
    name: http
    protocol: TCP
    nodePort: 30888
  type: LoadBalancer
---
